name: EcoTracker
version: '${project.version}'
main: com.playtheatria.jliii.ecotracker.EcoTracker
api-version: 1.19
commands:
  ecotracker:
    description: EcoTracker command
    usage: /<command> start <time>, /<command> clear
    aliases: [et]